{{- if gt (int .Values.server.workers) 0 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "presto.worker" . }}
  labels:
    app: {{ template "presto.name" . }}
    chart: {{ template "presto.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: worker
data:
  node.properties: |
    node.environment={{ .Values.server.node.environment }}
    node.data-dir={{ .Values.server.node.dataDir }}
    plugin.dir=/usr/lib/trino/plugin

  jvm.config: |
    -server
    -Xmx{{ .Values.server.jvm.maxHeapSize }}
    -XX:+{{ .Values.server.jvm.gcMethod.type }}
    -XX:G1HeapRegionSize={{ .Values.server.jvm.gcMethod.g1.heapRegionSize }}
    -XX:-UseBiasedLocking
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+UseGCOverheadLimit
    -XX:+ExitOnOutOfMemoryError
    -XX:ReservedCodeCacheSize=256M
    -Djdk.attach.allowAttachSelf=true
    -Djdk.nio.maxCachedBufferSize=2000000

  config.properties: |
    coordinator=false
    http-server.http.port={{ .Values.server.config.http.port }}
    query.max-memory={{ .Values.server.config.query.maxMemory }}
    discovery.uri=http://{{ template "presto.fullname" . }}:{{ .Values.service.port }}

  log.properties: |
    io.prestosql={{ .Values.server.log.presto.level }}

#  docker-presto.sh: |
#    #!/bin/bash
#    cp {{ .Values.server.config.path }}/*.properties $PRESTO_CONF_DIR
#    cp {{ .Values.server.config.path }}/*.config $PRESTO_CONF_DIR
#    cp {{ .Values.server.config.path }}/catalog/*properties $PRESTO_CONF_DIR/catalog
#    launcher run

#  health_check.sh: |
#    #!/bin/bash
#    curl --silent {{ template "presto.fullname" . }}:{{ .Values.service.port }}/v1/node | tr "," "\n" | grep --silent $(hostname -i)

---
{{- end }}
