apiVersion: v1
kind: Secret
metadata:
  name: {{ template "presto.catalog" . }}
  labels:
    app: {{ template "presto.name" . }}
    chart: {{ template "presto.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: catalog
type: Opaque
data:
{{ range $key, $val := .Values.server.catalog }}
  {{ $key }}: {{ $val | b64enc }}
{{ end }}
