{
 "title": "Druid",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queries Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "sum(increase(druid_broker_query_time_ms_count[1m])) by (datasource)",
     "legendFormat": "{{datasource}}"
    }
   ]
  },
  {
   "title": "Ingestion rows",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "wpm" }
   ],
   "targets": [
    {
     "expr": "sum(increase(druid_realtime_ingest_rows_output_count[1m])) by (datasource)",
     "legendFormat": "{{datasource}}"
    }
   ]
  },
  {
   "title": "Query Avg Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(increase(druid_broker_query_time_ms_sum[1m]) / increase(druid_broker_query_time_ms_count[1m])) by (datasource)",
     "legendFormat": "{{datasource}}"
    }
   ]
  },
  {
   "title": "Ingestion persists",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "wpm" }
   ],
   "targets": [
    {
     "expr": "sum(increase(druid_realtime_ingest_persists_count[1m])) by (datasource)",
     "legendFormat": "{{datasource}}"
    }
   ]
  },
  {
   "title": "Query Time Distribution",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "increase(druid_broker_query_time_ms_bucket[1m])"
    }
   ]
  },
  {
   "title": "Ingestion persists failures",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "wpm" }
   ],
   "targets": [
    {
     "expr": "sum(increase(druid_realtime_ingest_persists_failed_count[1m])) by (datasource)",
     "legendFormat": "{{datasource}}"
    }
   ]
  },
  { "title": "Segments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Segment state",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(druid_coordinator_segment_assigned_count[1m])",
     "legendFormat": "assigned"
    },
    {
     "expr": "increase(druid_coordinator_segment_moved_count[1m])",
     "legendFormat": "moved"
    },
    {
     "expr": "increase(druid_coordinator_segment_dropped_count[1m])",
     "legendFormat": "dropped"
    }
   ]
  },
  {
   "title": "Segments",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(druid_coordinator_segment_count) by (datasource)",
     "legendFormat": "{{datasource}}"
    }
   ]
  },
  {
   "title": "Datasource size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(druid_coordinator_segment_size_bytes) by (datasource)",
     "legendFormat": "{{datasource}}"
    }
   ]
  },
  {
   "title": "Datasource total size",
   "type": "graph",
   "description": "datasource total storage size with replication",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(druid_historical_segment_used_bytes{service=\"druid-historical-metrics\"}) by (datasource)",
     "legendFormat": "{{datasource}}"
    },
    {}
   ]
  }
 ]
}