dependencies:
- name: zookeeper
  version: 3.0.8
  repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
  condition: zookeeper.enabled
- name: postgresql
  version: 7.2.0
  repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
  condition: postgresql.enabled
