dependencies:
- name: zookeeper
  version: 1.4.2
  repository: https://charts.bitnami.com/bitnami
  condition: zookeeper.enabled
- name: postgresql
  version: 7.2.0
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
