dependencies:
- name: zookeeper
  version: 11.4.11
  repository: https://charts.bitnami.com/bitnami
  condition: zookeeper.enabled
- name: postgresql
  version: 12.12.10
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
