dependencies:
- name: zookeeper
  version: 1.2.0
  repository: https://kubernetes-charts-incubator.storage.googleapis.com/
  condition: zookeeper.enabled
- name: postgresql
  version: 7.2.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: postgresql.enabled
