# Default values for druid.

image:
  repository: apache/druid
  tag: 0.17.0
  pullPolicy: IfNotPresent

extensions:
  loadList:
  - druid-histogram
  - druid-datasketches
  - druid-lookups-cached-global
  - postgresql-metadata-storage
  - druid-s3-extensions
  - druid-kafka-indexing-service
  - druid-parquet-extensions
  - druid-kinesis-indexing-service

# Common env vars
# service specific env will overwrite these values
env:
  # Deep storage
  # specify your bucket name for s3 deep storage & indexer logs
  # e.g.:
  #  druid_storage_type: s3
  #  druid_storage_bucket: <druid-deep-storage-bucket>
  #  druid_storage_baseKey: druid/segments
  #  druid_indexer_logs_type: s3
  #  druid_indexer_logs_s3Bucket: <druid-deep-storage-bucket>
  #  druid_indexer_logs_s3Prefix: druid/indexing-logs

  druid_coordinator_balancer_strategy: cachingCost

  druid_indexer_queue_startDelay: PT30S

  druid_indexer_runner_javaOptsArray: '["-server", "-Xmx1g", "-Xms1g", "-XX:MaxDirectMemorySize=3g", "-Duser.timezone=UTC", "-Dfile.encoding=UTF-8", "-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager"]'
  druid_processing_buffer_sizeBytes: "10000000"
  druid_processing_numMergeBuffers: "4"
  druid_processing_numThreads: "16"
  druid_server_maxSize: "8000000000"

  druid_worker_capacity: "4"
  druid_indexer_fork_property_druid_processing_numMergeBuffers: "2"
  druid_indexer_fork_property_druid_processing_buffer_sizeBytes: "10000000"
  druid_indexer_fork_property_druid_processing_numThreads: "1"


turnilo:
  replicaCount: 1
  name: turnilo
  version: 1.20.1
  serviceType: ClusterIP
  servicePort: 80
  ingress:
    enabled: false
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    path: /
    hosts:
    - chart-example.local
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}

router:
  managementProxy:
    enabled: true
  replicaCount: 1
  name: router
  port: 8888
  servicePort: 80
  serviceType: ClusterIP
  javaOpts:
  ingress:
    enabled: false
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    path: /
    hosts:
    - chart-example.local
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
  env: {}

broker:
  replicaCount: 1
  name: broker
  port: 8082
  serviceType: ClusterIP
  javaOpts:
  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    path: /
    hosts:
      - chart-example.local
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
  env:
    DRUID_XMX: 1g
    DRUID_XMS: 1g
    DRUID_MAXNEWSIZE: 250m
    DRUID_NEWSIZE: 250m
    DRUID_MAXDIRECTMEMORYSIZE: 6g

# coordinator also runs an overlord by default (master node)
coordinator:
  replicaCount: 1
  name: coordinator
  port: 8081
  serviceType: ClusterIP
  javaOpts:
  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    path: /
    hosts:
      - chart-example.local
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
  env:
    DRUID_XMX: 256m
    DRUID_XMS: 256m
#    DRUID_MAXNEWSIZE: 250m
#    DRUID_NEWSIZE: 250m
#    DRUID_MAXDIRECTMEMORYSIZE: 6g

historical:
  name: historical
  replicaCount: 1
  port: 8083
  serviceType: ClusterIP
  javaOpts:
  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    path: /
    hosts:
      - chart-example.local
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: "4Gi"
    # storageClass: "ssd"
  health:
    livenessInitialDelaySeconds: 120
    readinessInitialDelaySeconds: 120
  antiAffinity: "soft"
  nodeAffinity: {}
  nodeSelector: {}
  tolerations: []
  resources: {}
  podAnnotations: {}
  podDisruptionBudget:
    enabled: false
    # minAvailable: 2
    maxUnavailable: 1
  updateStrategy:
    type: RollingUpdate
  env:
    DRUID_XMX: 1g
    DRUID_XMS: 1g
    DRUID_MAXNEWSIZE: 250m
    DRUID_NEWSIZE: 250m
    DRUID_MAXDIRECTMEMORYSIZE: 6g

middleManager:
  name: middle-manager
  replicaCount: 1
  port: 8091
  serviceType: ClusterIP
  javaOpts:
  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    path: /
    hosts:
      - chart-example.local
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: "4Gi"
    # storageClass: "ssd"
  health:
    livenessInitialDelaySeconds: 60
    readinessInitialDelaySeconds: 60
  antiAffinity: "soft"
  nodeAffinity: {}
  nodeSelector: {}
  tolerations: []
  resources: {}
  podAnnotations: {}
  podDisruptionBudget:
    enabled: false
    # minAvailable: 2
    maxUnavailable: 1
  updateStrategy:
    type: RollingUpdate
  env: {}
#    DRUID_XMX: 1g
#    DRUID_XMS: 1g
#    DRUID_MAXNEWSIZE: 250m
#    DRUID_NEWSIZE: 250m
#    DRUID_MAXDIRECTMEMORYSIZE: 6172m

monitoring:
  enabled: false
  createServiceMonitor: true
  port: 8000

# ------------------------------------------------------------------------------
# Zookeeper:
# ------------------------------------------------------------------------------

# zkHosts: druid-zookeeper-headless:2181

zookeeper:
  enabled: true
  ## Environmental variables to set in Zookeeper
  ##
  env:
    ## The JVM heap size to allocate to Zookeeper
    ZK_HEAP_SIZE: "512M"
  ## Configure Zookeeper persistence
  persistence:
    enabled: true


# ------------------------------------------------------------------------------
# PostgreSql:
# ------------------------------------------------------------------------------
postgresql:
  enabled: true
  postgresqlPostgresPassword: druidroot
  postgresqlUsername: druid
  postgresqlPassword: druid
  postgresqlDatabase: druid
