apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "druid.overlord.fullname" . }}
  labels:
    app: {{ include "druid.name" . }}
    chart: {{ include "druid.chart" . }}
    component: {{ .Values.overlord.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.overlord.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "druid.name" . }}
      release: {{ .Release.Name }}
      component: {{ .Values.overlord.name }}
  template:
    metadata:
      labels:
        app: {{ include "druid.name" . }}
        release: {{ .Release.Name }}
        component: {{ .Values.overlord.name }}
      {{- with .Values.overlord.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
      {{- end }} 
    spec:
      containers:
        - name: {{ include "druid.overlord.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: [ "overlord" ]
          env:
          {{- if .Values.zookeeper.enabled }}
          - name: druid_zk_service_host
            value: {{ .Release.Name }}-zookeeper-headless:2181
          {{- else }}
          - name: druid_zk_service_host
            value: {{ .Values.zkHosts }}
          {{- end }}
          - name: druid_plaintextPort
            value: "{{ .Values.overlord.port }}"
          - name: druid_extensions_loadList
            value: {{ .Values.extensions.loadList | toJson | quote }}
          - name: JAVA_OPTS
            value: {{ .Values.overlord.javaOpts }}
          {{- range $key, $value :=  .Values.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.overlord.port }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 180
            httpGet:
              path: /status/health
              port: {{ .Values.overlord.port }}
          readinessProbe:
            initialDelaySeconds: 180
            httpGet:
              path: /status/health
              port: {{ .Values.overlord.port }}
          resources:
{{ toYaml .Values.overlord.resources | indent 12 }}
    {{- with .Values.overlord.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.overlord.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.overlord.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
