{{- if .Values.monitoring.createServiceMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "druid.fullname" . }}-monitor
  labels:
    app: {{ include "druid.name" . }}
    chart: {{ include "druid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    tier: bi
spec:
  selector:
    matchLabels:
      monitoring: enabled
  endpoints:
  - port: metrics
    interval: 30s
{{- end }}