server:
  workers: 2
  node:
    environment: k8s
    dataDir: /data/trino
  log:
    presto:
      level: INFO
  config:
    path: /usr/lib/trino/etc
    http:
      port: 8080
    query:
      maxMemory: "8GB"
  jvm:
    maxHeapSize: "16G"
    gcMethod:
      type: "UseG1GC"
      g1:
        heapRegionSize: "32M"
  catalog:
    log.properties: |
      connector.name=localfile
      trino-logs.http-request-log.location=/data/trino/var/log
      trino-logs.http-request-log.pattern=*.log

image:
  repository: trinodb/trino
  tag: 351
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
