apiVersion: v1
kind: Service
metadata:
  name: {{ include "druid.middleManager.fullname" . }}
  labels:
    app: {{ include "druid.name" . }}
    chart: {{ include "druid.chart" . }}
    component: {{ .Values.middleManager.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.middleManager.serviceType }}
  ports:
    - port: {{ .Values.middleManager.port }}
      targetPort: http
      protocol: TCP
      name: http
{{- range untilStep 100 199 1 }}
    - port: 8{{ . }}
      targetPort: 8{{ . }}
      name: port-8{{ . }}
      protocol: TCP
{{- end }}

  selector:
    app: {{ include "druid.name" . }}
    release: {{ .Release.Name }}
    component: {{ .Values.middleManager.name }}
